TRUNCATE TABLE `tanah` ;
TRUNCATE TABLE `bangunan` ;
TRUNCATE TABLE `jaringan` ;
TRUNCATE TABLE `kdp` ;
TRUNCATE TABLE `asetlain` ;
TRUNCATE TABLE `mesin` ;
TRUNCATE TABLE `aset` ;
TRUNCATE TABLE `kontrak` ;
TRUNCATE TABLE `sp2d` ;
TRUNCATE TABLE `sp2d_rinc` ;
TRUNCATE TABLE `transfer` ;
TRUNCATE TABLE `transferaset` ;
TRUNCATE TABLE `usulan` ;
TRUNCATE TABLE `usulanaset` ;
TRUNCATE TABLE `penggunaan` ;
TRUNCATE TABLE `penggunaanaset` ;
TRUNCATE TABLE `pemanfaatan` ;
TRUNCATE TABLE `pemanfaatanaset` ;
TRUNCATE TABLE `penghapusan` ;
TRUNCATE TABLE `penghapusanaset` ;
TRUNCATE TABLE `log_aset` ;
TRUNCATE TABLE `log_asetlain`;
TRUNCATE TABLE `log_bangunan`;
TRUNCATE TABLE `log_jaringan`;
TRUNCATE TABLE `log_kdp`;
TRUNCATE TABLE `log_kontrak`;
TRUNCATE TABLE `log_mesin`;
TRUNCATE TABLE `log_sp2d`;
TRUNCATE TABLE `log_sp2d_rinc`;
TRUNCATE TABLE `log_tanah`;
